### ISSUE TITLE
discharge_summaries_labels.csv includes nursing labels

### ISSUE THREAD

**Issue by admatis** [bvanaken/clinical-assertion-data#1]
both discharge_summaries_labels.csv and nursing_labels.csv contain the nursing labels
where can I find the discharge summaries labels?

thanks

**Comment by bvanaken** [comment]
Hi admatis,

thank you so much for pointing us towards this. There was a simple mistake while uploading and I now replaced the discharge summaries file to contain the actual discharge labels.
Again, thanks for your help and I hope the labels are of use for you!

Best, Betty
