### ISSUE TITLE
Demo site is down & Is it possible to release the model

### ISSUE THREAD

**Issue by Kevinweisl** [bvanaken/clinical-assertion-data#2]
It seems the demo site mentioned in "Assertion Detection in Clinical Notes: Medical Language Models to the Rescue?" is not available. Will it open again for some simple trials?

On the other hand, this work may be helpful as the preprocessing part of other clinical applications. Is it possible to release the code and the model mentioned in the paper?

Thanks.

**Comment by bvanaken** [comment]
Hi,

Thanks for reaching out. We had a few days of downtime, but now the demo is back [online](https://ehr-assertion-detection.demo.datexis.com)!
We will also release the best model to the huggingface model hub within the next days, I'll send an update once it's available.

Best, Betty

**Comment by bvanaken** [comment]
Hi,

you can now download our best assertion/negation classification model based on Discharge Summary BERT at the huggingface model hub:
https://huggingface.co/bvanaken/clinical-assertion-negation-bert

**Comment by Kevinweisl** [comment]
It's awesome to get your best model on huggingface.  
It may be beneficial to leverage your research to other clinical downstream works. 

However, I wonder that how to use your model to reproduce the functionality of your demo site? In other words, I would like to input a piece of clinical text and expect the output is a list of assertions.

**Comment by bvanaken** [comment]
Hi,
I added a model [inference script](https://github.com/bvanaken/clinical-assertion-data/blob/main/model/inference.py) to show how we create lists of assertions from clinical input text. The entitiy recognition is done with scispacy which is of course interchangable. Hope this helps!
